### ISSUE TITLE
Must specify a Content-Type header with POST requests - Solr 4.7

### ISSUE THREAD

**Issue by ChrisLomax** [SolrNet/SolrNet#142]
I've just installed a new BitNami / Solr stack with 4.7 installed and tried to use the latest SolrNet.

Previous code that worked to push PDFs into the index no longer works, I receive the error above. Other documents work fine.

I've seen this bug post on Apache https://issues.apache.org/jira/browse/SOLR-5517 that states that Solr will throw an error when no content-type is set in the header and I also tried manually setting the content-type in SolrConntection.cs PostStream to "application/x-www-form-urlencoded" as per site http://qnalist.com/questions/4765256/updated-to-v4-7-getting-search-requests-cannot-accept-content-streams.

I rolled out a new version with this in place and it still did not index the documents.

Stack trace of error 

[System.Net.WebException: The remote server returned an error: (415) Unsupported Media Type.]
at System.Net.HttpWebRequest.GetResponse()
at HttpWebAdapters.Adapters.HttpWebRequestAdapter.GetResponse()
at SolrNet.Impl.SolrConnection.GetResponse(IHttpWebRequest request)
at SolrNet.Impl.SolrConnection.PostStream(String relativeUrl, String contentType, Stream content, IEnumerable`1 parameters)

[SolrNet.Exceptions.SolrConnectionException: Must specify a Content-Type header with POST requests415 ]
at SolrNet.Impl.SolrConnection.PostStream(String relativeUrl, String contentType, Stream content, IEnumerable`1 parameters)
at SolrNet.Commands.ExtractCommand.Execute(ISolrConnection connection)
at SolrNet.Impl.SolrBasicServer`1.Send(ISolrCommand cmd)
at SolrNet.Impl.SolrBasicServer`1.SendAndParseExtract(ISolrCommand cmd)
at SolrNet.Impl.SolrBasicServer`1.Extract(ExtractParameters parameters)
at SolrNet.Impl.SolrServer`1.Extract(ExtractParameters parameters)
at Every1.Ticker.Core.Web.Search.AddResource(spResourcesForIndexResult resource)

**Comment by xavier-morera** [comment]
Current issue has been closed as part of cleanup process, which is tracked in https://github.com/SolrNet/SolrNet/issues/338. 

Please reopen if needed, hopefully helping bringing up to date with current code.
