### ISSUE TITLE
Issue with CommonServiceLocator v2.0.1

### ISSUE THREAD

**Issue by mpctilsted** [SolrNet/SolrNet#326]
**Dependencies:**

```
  <package id="Autofac" version="4.6.2" targetFramework="net461" />
  <package id="Autofac.Extras.CommonServiceLocator" version="5.0.0" targetFramework="net461" />
  <package id="CommonServiceLocator" version="2.0.1" targetFramework="net461" />
  <package id="SolrNet" version="0.8.1" targetFramework="net461" />
  <package id="SolrNet.Autofac" version="0.8.1" targetFramework="net461" />
  <package id="SolrNet.Core" version="0.8.1" targetFramework="net461" />
```

**Registering module and setting servicelocator:**

```
builder.RegisterModule(new SolrNetModule(cores));
ServiceLocator.SetLocatorProvider(() => new AutofacServiceLocator(container));
```

**Throw me this error:**

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SolrNet.Startup' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Practices.ServiceLocation, Version=1.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at SolrNet.Startup..cctor()
   --- End of inner exception stack trace ---
   at SolrNet.Startup.Init[T](String serverURL)
```

**Can anyone else confirm this, or am i just doing it wrong?**

**Comment by mpctilsted** [comment]
Sorry, it was me doing it wrong. 
You shouldn't directly call Startup method when injecting solr operation with Autofac.
My mistake.
