### ISSUE TITLE
Unexpected end of file while doing an Extract?

### ISSUE THREAD

**Issue by bifflog** [SolrNet/SolrNet#471]
I am experiencing issue frequently with exception occurring during Extract only of a PDF document.  Here is the solr response:

<response>

<lst name="responseHeader">
  <int name="status">500</int>
  <int name="QTime">6854</int>
</lst>
<lst name="error">
  <lst name="metadata">
    <str name="error-class">org.apache.solr.common.SolrException</str>
    <str name="root-error-class">java.io.IOException</str>
  </lst>
  <str name="msg">org.apache.tika.exception.TikaException: Unable to extract PDF content</str>
  <str name="trace">org.apache.solr.common.SolrException: org.apache.tika.exception.TikaException: **Unable to extract PDF content**
                at org.apache.solr.handler.extraction.ExtractingDocumentLoader.load(ExtractingDocumentLoader.java:234)
                at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
                at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:199)
                at org.apache.solr.core.SolrCore.execute(SolrCore.java:2541)
                at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:709)
                at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:515)
                at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:377)
                at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:323)
                at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
                at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
                at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
                at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
                at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
                at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
                at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
                at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
                at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
                at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
                at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
                at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
                at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
                at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
                at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
                at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:335)
                at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
                at org.eclipse.jetty.server.Server.handle(Server.java:531)
                at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
                at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
                at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
                at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
                at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
                at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
                at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
                at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
                at java.lang.Thread.run(Unknown Source)
**Caused by: org.apache.tika.exception.TikaException: Unable to extract PDF content**
                at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:139)
                at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:172)
                at org.apache.solr.handler.extraction.ExtractingDocumentLoader.load(ExtractingDocumentLoader.java:228)
                ... 41 more
**Caused by: java.io.IOException: Error: End-of-File, expected line**
                at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1119)
                at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:2582)
                at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:2553)
                at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:213)
                at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1160)
                at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1133)
                at org.apache.tika.parser.pdf.PDFParser.parse(PDFParser.java:154)
                at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72)
                at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:102)
                at org.apache.tika.parser.pdf.AbstractPDF2XHTML.extractPDEmbeddedFile(AbstractPDF2XHTML.java:277)
                at org.apache.tika.parser.pdf.AbstractPDF2XHTML.extractMultiOSPDEmbeddedFiles(AbstractPDF2XHTML.java:235)
                at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processDoc(AbstractPDF2XHTML.java:212)
                at org.apache.tika.parser.pdf.AbstractPDF2XHTML.processEmbeddedDocNames(AbstractPDF2XHTML.java:223)
                at org.apache.tika.parser.pdf.AbstractPDF2XHTML.extractEmbeddedDocuments(AbstractPDF2XHTML.java:196)
                at org.apache.tika.parser.pdf.AbstractPDF2XHTML.endDocument(AbstractPDF2XHTML.java:537)
                at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:267)
                at org.apache.tika.parser.pdf.PDF2XHTML.process(PDF2XHTML.java:117)
                ... 43 more
</str>
  <int name="code">500</int>
</lst>
</response>

And my snippet of code that calls extract:

`
            MemoryStream fileToExtractFrom = new MemoryStream(file);
            string type = "application/pdf";

            using (fileToExtractFrom)
            {
                fileToExtractFrom.Seek(0, SeekOrigin.Begin);

                var response = await solr.ExtractAsync(new ExtractParameters(fileToExtractFrom, "", "test")
                {
                    StreamType = type,
                    ExtractOnly = true,
                    ExtractFormat = ExtractFormat.Text
                });

`

This error does not always occur, and there are plenty PDF's I am able to extract from.  Furthermore, the problematic PDF's when using the library, are not so when uploaded through the solr web interface using update/extract, they get properly parsed and indexed.  So I am a bit stumped, any help on this?

**Comment by robhford** [comment]
> I have experienced something similar a few times. First step is to rule out if size is the issue and where.
> 
> Can you identify files of certain size and try to determine if files of larger size are being truncated? This includes testing with files of varying sizes.

Thanks for taking a look!

File size seems to not have much to do with it, I am primarily seeing PDFs of varying sizes (2MB-25MB) and a particular docx that is very large 100MB+.  Some files fail sometimes, some files fail all the time, and there are certainly larger files succeeding than a few of those that always fail.  

I cam across this snippet when researching this problem:
