### ISSUE TITLE
SolrNet.Exceptions.SolrConnectionException: The operation has timed out ---> System.Net.WebException: The operation has timed out

### ISSUE THREAD

**Issue by sergiocharpineljr** [SolrNet/SolrNet#510]
Recently I'm receiving exceptions like this:

SolrNet.Exceptions.SolrConnectionException
The operation has timed out
SolrNet.Exceptions.SolrConnectionException: The operation has timed out ---> System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at HttpWebAdapters.Adapters.HttpWebRequestAdapter.GetResponse()
   at SolrNet.Impl.SolrConnection.GetResponse(IHttpWebRequest request)
   at SolrNet.Impl.SolrConnection.PostStream(String relativeUrl, String contentType, Stream content, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at SolrNet.Impl.SolrConnection.PostStream(String relativeUrl, String contentType, Stream content, IEnumerable`1 parameters)
   at SolrNet.Impl.SolrConnection.Post(String relativeUrl, String s)
   at SolrNet.Impl.LowLevelSolrServer.SendAndParseHeader(ISolrCommand cmd)
...

At the Solr server side I get:
2020-01-20 18:57:58.665 INFO  (qtp1668016508-67244) [   x:<MY CORE>] o.a.s.u.p.LogUpdateProcessorFactory [<MY CORE>]  webapp=/solr path=/update params={version=2.2&wt=xml}**{} 0 257736**
2020-01-20 18:57:58.666 ERROR (qtp1668016508-67244) [   x:<MY CORE>] o.a.s.h.RequestHandlerBase [com.ctc.wstx.exc.WstxLazyException] com.ctc.wstx.exc.WstxIOException: Early EOF
        at com.ctc.wstx.exc.WstxLazyException.throwLazily(WstxLazyException.java:45)
        at com.ctc.wstx.sr.StreamScanner.throwLazyError(StreamScanner.java:728)
        at com.ctc.wstx.sr.BasicStreamReader.safeFinishToken(BasicStreamReader.java:3678)
        at com.ctc.wstx.sr.BasicStreamReader.getText(BasicStreamReader.java:860)
        at org.apache.solr.handler.loader.XMLLoader.readDoc(XMLLoader.java:419)
        at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:260)
        at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
...

The strange thing is that the "add=<docid>" is missing in the log entry preceding the exception. 

Seems like SolrNET client's connection is timing out and closes the connection with the server. The server returns the Early EOF exception.

The server resources are not under pressure.

I tried the suggestions from https://groups.google.com/forum/#!topic/solrnet/3-oT18kAg74, but the timeouts remains.

Any suggestions?

**Comment by xmorera** [comment]
Can you open Fiddler or another traffic analyzer and get the exact call that was made?

That can help understand the issue better and I can help you find a solution.

-   Xavier -

**Comment by sergiocharpineljr** [comment]
I think I can't capture the traffic. We could only reproduce in production, it show up randomly (even with low traffic) and we are using HTTPS.

**Comment by xmorera** [comment]
Early EOF has happened to me a few times when the request is really long and since the call is using GET and not POST then the request is being truncated. Are you sending a very large request?

-   Xavier -

**Comment by sergiocharpineljr** [comment]
The requests are updates, using POST. And after some retries the update works.

**Comment by xmorera** [comment]
Ok. I did not know it worked after a few times. Mine was a different scenario but I wanted to mention it.

Coming back to your problem as I got distracted by one I ran into a little bit ago.

At a high level, I would log all calls made by SolrNet to find first if there is an issue with what is sent-you mentioned the add= seems to be missing. If this is the case, then figure out why.

If no change, then would move on into troublshooting the Solr instance.



-   Xavier -

**Comment by sergiocharpineljr** [comment]
We have 4 threads addind documents to Solr simultaneously. We observed that the timeouts are more likely to happen when there are simultaneous connections with big documents (such as 4MB of text).

Do you know if there is any limits on the number os connections? What is the default timeout of the requests when I let SolrConnection.Timeout = -1?

**Comment by xmorera** [comment]
Yes, there are limits but it should be more than 4. I believe the default is 20 max connections per host.

Can you try increasing timeout?

**Comment by sergiocharpineljr** [comment]
I did. Some update requests are taking more than 10 minutes to execute. But not always. Seems like Solr is executing some backgrounds jobs that makes these updates slower. We will investigate GC and segments merging.

So I think it is not related to SolrNet.

Xavier, thanks for you help.

**Comment by hamzadsmart** [comment]
which file is used for configuration
