### ISSUE TITLE
SolrNet.Exceptions.SolrConnectionException: Only one usage of each socket address (protocol/network address/port) is normally permitted.

### ISSUE THREAD

**Issue by bo11zhou** [SolrNet/SolrNet#512]
2020-02-20 12:03:54.700 +08:00 [Error] An unhandled exception has occurred while executing the request.
SolrNet.Exceptions.SolrConnectionException: Only one usage of each socket address (protocol/network address/port) is normally permitted. Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.WebException: Only one usage of each socket address (protocol/network address/port) is normally permitted. Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Http.HttpRequestException: Only one usage of each socket address (protocol/network address/port) is normally permitted.
 ---> System.Net.Sockets.SocketException (10048): Only one usage of each socket address (protocol/network address/port) is normally permitted.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at System.Net.HttpWebRequest.SendRequest()
   at System.Net.HttpWebRequest.GetResponse()
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at HttpWebAdapters.Adapters.HttpWebRequestAdapter.GetResponse()
   at SolrNet.Impl.PostSolrConnection.Get(String relativeUrl, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at SolrNet.Impl.PostSolrConnection.Get(String relativeUrl, IEnumerable`1 parameters)
   at SolrNet.Impl.SolrQueryExecuter`1.Execute(ISolrQuery q, QueryOptions options)
   at CMS.Solr.IRepositories.TagRepository.Search(SearchParameters parameters) in C:\MyWork\NTT Project Git\CMSWebApi1116\CMS-WebAPI\CMS.Solr\Repositories\TagRepository.cs:line 30
   at CMS.WebApi.Common.ApiUnit.GetTags(String lang) in C:\MyWork\NTT Project Git\CMSWebApi1116\CMS-WebAPI\WebApi\Common\ApiUnit.cs:line 115
   at CMS.WebApi.v1.Controllers.ContentController.GetBaseInfo(String lang) in C:\MyWork\NTT Project Git\CMSWebApi1116\CMS-WebAPI\WebApi\Controllers\v1\ContentController.cs:line 799
   at CMS.WebApi.v1.Controllers.ContentController.GetList(ContentPageQuery query) in C:\MyWork\NTT Project Git\CMSWebApi1116\CMS-WebAPI\WebApi\Controllers\v1\ContentController.cs:line 389
   at CMS.WebApi.v1.Controllers.ContentController.GetContent(ContentPageQuery query) in C:\MyWork\NTT Project Git\CMSWebApi1116\CMS-WebAPI\WebApi\Controllers\v1\ContentController.cs:line 87

What's the problem:
A. application side has wrong solr connection configuration?
B. Any wrong configuration exist in the remote Solr servers?

**Comment by arthurbai** [comment]
Is there anyone udated for this QA?

**Comment by gjunge** [comment]
Is this somehow related perhaps? 

Seems like the webrequest fails due to some other requests binding to the same port it tried to use.

https://stackoverflow.com/questions/26428827/httpclient-only-one-usage-of-each-socket-address-protocol-network-address-port

**Comment by arthurbai** [comment]
> Is this somehow related perhaps?
> 
> Seems like the webrequest fails due to some other requests binding to the same port it tried to use.
> 
> https://stackoverflow.com/questions/26428827/httpclient-only-one-usage-of-each-socket-address-protocol-network-address-port

Dear,

We didn't use http client to access solr directly, we just use solr.net to query data from solr,

and we found it  always be happend on concurrent situation,   but solr connecton seem be singlton pattern on solr.net . 

Could you give us some suggestions?

thanks.

**Comment by lisamariet** [comment]
We are experiencing the same problem. Would be nice with some update.
