### ISSUE TITLE
SolrNet Cloud Resiliency: if ZooKeeper init fails once, it fails forever.

### ISSUE THREAD

**Issue by Wintermute79** [SolrNet/SolrNet#589]
For some reason I have an irregular, transient problem with a few of my ZooKeeper connections. In effect, I cannot get a collection state for a short while a few times a day.
However, I do not want to address _this issue_ here; I opened an issue in ZooKeeper .NET Client repo at https://github.com/shayhatsor/zookeeper/issues/48 instead.

What _I would like to address_ in SolrNet Cloud, is resiliency: I want to be able to recover from this short, irregular and temporary error.
If we cannot get a collection state from ZooKeeper upon init, the internal state in `SolrCloudStateProvider` remains empty forever and all subsequent queries fail. So the same error occurs forever until the app is restarted and SolrNet Cloud can be re-initialized:

```
System.ApplicationException: Didn't get any collection's state from zookeeper.
   at SolrNet.Cloud.SolrCloudOperationsBase`1.SelectReplicas(Boolean leaders) in C:\Visual Studio\SolrNet\SolrNet.Cloud\SolrCloudOperationsBase.cs:line 90
   at SolrNet.Cloud.SolrCloudOperationsBase`1.PerformOperation[TResult](Func`2 operation, Boolean leader) in C:\Visual Studio\SolrNet\SolrNet.Cloud\SolrCloudOperationsBase.cs:line 72
   at SolrNet.Cloud.SolrCloudOperations`1.QueryAsync(ISolrQuery query, QueryOptions options, CancellationToken cancellationToken) in C:\Visual Studio\SolrNet\SolrNet.Cloud\SolrCloudOperations.cs:line 419

```
The internal state is set in `ZooKeeperClient.SolrCloudStateProvider.InitAsync()`:

https://github.com/SolrNet/SolrNet/blob/4e04cd49f75aaeca8ff3a3280fef6bf719980509/SolrNet.Cloud/ZooKeeperClient/SolrCloudStateProvider.cs#L84

which is called only once during dependency injection. From this point on it will remain useless if failed.

However there is a method `GetFreshCloudStateAsync()` which could be used to refresh the state later at any time:
https://github.com/SolrNet/SolrNet/blob/4e04cd49f75aaeca8ff3a3280fef6bf719980509/SolrNet.Cloud/ZooKeeperClient/SolrCloudStateProvider.cs#L123
But it has a comment reading:

> Reinitialize connection and get fresh cloud state.
> Not included in ISolrCloudStateProvider interface due to the testing purpose only
> (causes reloading all cloud data and too slow to use in production)
> 

What I want to propose is to actually DO INCLUDE this method in interface `ISolrCloudStateProvider` so that we can recover from such problem without the need to restart a whole app.

**Comment by Wintermute79** [comment]
Done in #590
