### ISSUE TITLE
Cannot connect to the Zookeeper instance <connectionString>. Current state: CONNECTING

### ISSUE THREAD

**Issue by kostas-kelgeorgiadis** [SolrNet/SolrNet#603]
We are getting this weird error at random times while using the library on a Solr Cloud installation with a ZK enclave of 3 ZK nodes:

> SolrNet.Cloud.Exceptions.SolrNetCloudConnectionException: Cannot connect to the Zookeeper instance zk1.local.net:2181,zk2.local.net:2181,zk3.local.net:2181/solr. Current state: CONNECTING 
   at SolrNet.Cloud.ZooKeeperClient.SolrCloudStateProvider.<InitAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

I see it comes from the code added here (although, I haven't managed to find yet on which branch it is applied - it seemed missing from `master` and `develop`):
https://github.com/SolrNet/SolrNet/pull/388/files

Any idea why the connection goes into a `CONNECTING` state?
I have tried using the `ZookeeperNetEx` package to hit directly ZK and it worked, at the same time that the `SolrNet.Cloud` library was failing.

**Comment by kostas-kelgeorgiadis** [comment]
OK, I see now that the check creating the problem was removed with this commit: c1b7d9147208a401d08eb268eafeae84f6e517aa.
Perhaps the latest version of the library might fix the problem.
I will test.

**Comment by kostas-kelgeorgiadis** [comment]
With the latest library code, it appears that the error location is shifted and it is manifested with a different error message:

```
System.ApplicationException: Didn't get any collection's state from zookeeper.
   at SolrNet.Cloud.SolrCloudOperationsBase`1.SelectReplicas(Boolean leaders)
   at SolrNet.Cloud.SolrCloudOperationsBase`1.PerformOperation[TResult](Func`2 operation, Boolean leader)
   at SolrNet.Cloud.SolrCloudOperations`1.Query(ISolrQuery query, QueryOptions options)
```

But, apparently, the underlying problem is the same: the communication with ZooKeeper is not ready/feasible.

**Comment by kostas-kelgeorgiadis** [comment]
I have the impression (without testing or verifying this) that the problem is in this method:

https://github.com/SolrNet/SolrNet/blob/2007603ef826d07fd3714f669462d9c463b05c21/SolrNet.Cloud/ZooKeeperClient/SolrCloudStateProvider.cs#L161

...and that the code should look more like this example:
https://github.com/shayhatsor/zookeeper/blob/trunk/docs/javaExample.html#L532

So, something along these lines:

```
        public override async Task process(WatchedEvent @event)
        {
            var eventType = @event.get_Type();

            if (eventType != Event.EventType.None)
            {
                // Something has changed on the nodes. Let's update.
                await SynchronizedUpdateAsync().ConfigureAwait(false);
            }
            else if (eventType == Event.EventType.None)
            {
                // We are are being told that the state of the connection has changed.
                var keeperState = @event.getState();
                if (keeperState == Event.KeeperState.Disconnected || keeperState == Event.KeeperState.Expired)
                {
                    await SynchronizedUpdateAsync(cleanZookeeperConnection: true).ConfigureAwait(false);
                }
            }
        }
```

Notice the handling of the Expired state, the changed if/else flow, and the not checking on the value of `@event.getPath()` to update the live nodes.
I have not tested this code however.
So, perhaps I will do that and then come back with a PR.

**Comment by kostas-kelgeorgiadis** [comment]
BTW, when getting the `Didn't get any collection's state from zookeeper.` error, zookeeper seems to log this error:

```
2022-09-14 08:58:03.978 WARN  (NIOWorkerThread-4) [   ] o.a.z.s.NIOServerCnxn Unexpected exception => EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:52520, session = 0x0
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163)
org.apache.zookeeper.server.ServerCnxn$EndOfStreamException: Unable to read additional data from client, it probably closed the socket: address = /127.0.0.1:52520, session = 0x0
        at org.apache.zookeeper.server.NIOServerCnxn.handleFailedRead(NIOServerCnxn.java:163) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:326) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.server.NIOServerCnxnFactory$IOWorkRequest.doWork(NIOServerCnxnFactory.java:522) ~[zookeeper-3.6.2.jar:3.6.2]
        at org.apache.zookeeper.server.WorkerService$ScheduledWorkRequest.run(WorkerService.java:154) ~[zookeeper-3.6.2.jar:3.6.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_341]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_341]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_341]
```

**Comment by kostas-kelgeorgiadis** [comment]
It turns out that the source of the problem was a low timeout setting for the `SolrCloudStateProvider`.
I wonder though, if the code should retry to establish the connection, because in my case it was working some of the times.
So, it was not like it was impossible to establish a connection, but it just happened to fail the first time and got stuck at the CONNECTING state.
